### ISSUE TITLE
"Benchmark" dataset missing

### ISSUE THREAD

**Issue by Deanzou** [FSUHeting/FSU_DL_LOB_Trading#1]
Hi，

The link of "Benchmark" dataset is unavaliable .  would you plz upload it  again？ Thanks a lot

**Comment by FSUHeting** [comment]
Hi, the "Benchmark" dataset is from this paper:

Benchmark dataset for mid-price forecasting of limit orderbook data with machine learning methods.
Adamantios Ntakaris, Martin Magris, Juho Kanniainen, Moncef Gabbouj, Alexandros Iosifidis. (2018)
https://onlinelibrary.wiley.com/doi/epdf/10.1002/for.2543

When I was doing the experiment, the data is available online. The data was too big. That's why I did not upload the data. I did not keep a copy of the data because I thought everyone can download it. 

This professor "Moncef Gabbouj" published many paper based on that dataset. Maybe you can contact the professor to get a copy of the data.

**Comment by Deanzou** [comment]
Hi 

Thanks for your  detailed answer. So kind of you .
